LIB_DIR   := ../../lib
SHARE_DIR := ../../share

.PHONY: default
default: build-setup-py

.PHONY: clean
clean: clean-setup-py

.PHONY: install
install: default install-setup-py

include $(LIB_DIR)/mk/python.mk
