"""empty message

Revision ID: 08df8985eb77
Revises: 
Create Date: 2018-01-23 01:39:38.151790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08df8985eb77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_to_license',
    sa.Column('license_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('group_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['license.id'], )
    )
    op.create_table('installed_app',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_read_0', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('_permissions_read_1', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('_permissions_write_0', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('_permissions_write_1', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('_permissions_delete_0', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('_permissions_delete_1', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('app_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('config', sa.dialects.postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installed_app__permissions_delete_0'), 'installed_app', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_installed_app__permissions_delete_1'), 'installed_app', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_installed_app__permissions_read_0'), 'installed_app', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_installed_app__permissions_read_1'), 'installed_app', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_installed_app__permissions_write_0'), 'installed_app', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_installed_app__permissions_write_1'), 'installed_app', ['_permissions_write_1'], unique=False)
    op.create_table('profile_to_license',
    sa.Column('license_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('profile_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['license.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_to_license')
    op.drop_index(op.f('ix_installed_app__permissions_write_1'), table_name='installed_app')
    op.drop_index(op.f('ix_installed_app__permissions_write_0'), table_name='installed_app')
    op.drop_index(op.f('ix_installed_app__permissions_read_1'), table_name='installed_app')
    op.drop_index(op.f('ix_installed_app__permissions_read_0'), table_name='installed_app')
    op.drop_index(op.f('ix_installed_app__permissions_delete_1'), table_name='installed_app')
    op.drop_index(op.f('ix_installed_app__permissions_delete_0'), table_name='installed_app')
    op.drop_table('installed_app')
    op.drop_table('group_to_license')
    # ### end Alembic commands ###
