"""empty message

Revision ID: 879e94e29655
Revises: edb1f4bba89e
Create Date: 2018-02-06 20:24:41.729650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '879e94e29655'
down_revision = 'edb1f4bba89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app', 'desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('app', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('app', 'slug',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('app', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('installed_app', 'app_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('installed_app', 'app_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('app', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('app', 'slug',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('app', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('app', 'desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
