"""empty message

Revision ID: 8c0968acb34f
Revises: 
Create Date: 2018-04-21 20:36:33.420464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence


# revision identifiers, used by Alembic.
revision = '8c0968acb34f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(CreateSequence(Sequence('profiles_to_license_seq')))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directorofme_auth_app',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_delete_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_delete_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_write_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_write_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_1', sa.String(length=50), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('callback_url', sa.String(length=255), nullable=True),
    sa.Column('config_schema', sa.dialects.postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_directorofme_auth_app__permissions_delete_0'), 'directorofme_auth_app', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_app__permissions_delete_1'), 'directorofme_auth_app', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_app__permissions_read_0'), 'directorofme_auth_app', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_app__permissions_read_1'), 'directorofme_auth_app', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_app__permissions_write_0'), 'directorofme_auth_app', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_app__permissions_write_1'), 'directorofme_auth_app', ['_permissions_write_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_app_slug'), 'directorofme_auth_app', ['slug'], unique=True)
    op.create_table('directorofme_auth_group',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_delete_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_delete_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_write_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_write_1', sa.String(length=50), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=48), nullable=False),
    sa.Column('type', sa.Enum('system', 'scope', 'feature', 'data', name='grouptypes'), nullable=False),
    sa.Column('scope_name', sa.String(length=48), nullable=True),
    sa.Column('scope_permission', sa.String(length=46), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name', 'type'),
    sa.UniqueConstraint('scope_name', 'scope_permission')
    )
    op.create_index(op.f('ix_directorofme_auth_group__permissions_delete_0'), 'directorofme_auth_group', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_group__permissions_delete_1'), 'directorofme_auth_group', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_group__permissions_read_0'), 'directorofme_auth_group', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_group__permissions_read_1'), 'directorofme_auth_group', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_group__permissions_write_0'), 'directorofme_auth_group', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_group__permissions_write_1'), 'directorofme_auth_group', ['_permissions_write_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_group_name'), 'directorofme_auth_group', ['name'], unique=True)
    op.create_index(op.f('ix_directorofme_auth_group_scope_name'), 'directorofme_auth_group', ['scope_name'], unique=False)
    op.create_table('directorofme_auth_group_to_group',
    sa.Column('parent_group_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('member_group_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['member_group_id'], ['directorofme_auth_group.id'], ),
    sa.ForeignKeyConstraint(['parent_group_id'], ['directorofme_auth_group.id'], )
    )
    op.create_table('directorofme_auth_installed_app',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_delete_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_delete_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_write_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_write_1', sa.String(length=50), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('app_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('config', sa.dialects.postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['directorofme_auth_app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directorofme_auth_installed_app__permissions_delete_0'), 'directorofme_auth_installed_app', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_installed_app__permissions_delete_1'), 'directorofme_auth_installed_app', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_installed_app__permissions_read_0'), 'directorofme_auth_installed_app', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_installed_app__permissions_read_1'), 'directorofme_auth_installed_app', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_installed_app__permissions_write_0'), 'directorofme_auth_installed_app', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_installed_app__permissions_write_1'), 'directorofme_auth_installed_app', ['_permissions_write_1'], unique=False)
    op.create_table('directorofme_auth_license',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_delete_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_delete_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_write_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_write_1', sa.String(length=50), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('managing_group_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('valid_through', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['managing_group_id'], ['directorofme_auth_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directorofme_auth_license__permissions_delete_0'), 'directorofme_auth_license', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_license__permissions_delete_1'), 'directorofme_auth_license', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_license__permissions_read_0'), 'directorofme_auth_license', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_license__permissions_read_1'), 'directorofme_auth_license', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_license__permissions_write_0'), 'directorofme_auth_license', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_license__permissions_write_1'), 'directorofme_auth_license', ['_permissions_write_1'], unique=False)
    op.create_table('directorofme_auth_profile',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_delete_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_delete_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_write_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_write_1', sa.String(length=50), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('preferences', sa.dialects.postgresql.JSON(), nullable=True),
    sa.Column('group_of_one_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_of_one_id'], ['directorofme_auth_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_directorofme_auth_profile__permissions_delete_0'), 'directorofme_auth_profile', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_profile__permissions_delete_1'), 'directorofme_auth_profile', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_profile__permissions_read_0'), 'directorofme_auth_profile', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_profile__permissions_read_1'), 'directorofme_auth_profile', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_profile__permissions_write_0'), 'directorofme_auth_profile', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_profile__permissions_write_1'), 'directorofme_auth_profile', ['_permissions_write_1'], unique=False)
    op.create_table('directorofme_auth_requested_scopes',
    sa.Column('app_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('group_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['directorofme_auth_app.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['directorofme_auth_group.id'], )
    )
    op.create_table('directorofme_auth_granted_scopes',
    sa.Column('installed_app_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('group_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['directorofme_auth_group.id'], ),
    sa.ForeignKeyConstraint(['installed_app_id'], ['directorofme_auth_installed_app.id'], )
    )
    op.create_table('directorofme_auth_group_to_license',
    sa.Column('license_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('group_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['directorofme_auth_group.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['directorofme_auth_license.id'], )
    )
    op.create_table('directorofme_auth_profile_to_license',
    sa.Column('license_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('profile_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['directorofme_auth_license.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['directorofme_auth_profile.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directorofme_auth_profile_to_license')
    op.drop_table('directorofme_auth_group_to_license')
    op.drop_table('directorofme_auth_granted_scopes')
    op.drop_table('directorofme_auth_requested_scopes')
    op.drop_index(op.f('ix_directorofme_auth_profile__permissions_write_1'), table_name='directorofme_auth_profile')
    op.drop_index(op.f('ix_directorofme_auth_profile__permissions_write_0'), table_name='directorofme_auth_profile')
    op.drop_index(op.f('ix_directorofme_auth_profile__permissions_read_1'), table_name='directorofme_auth_profile')
    op.drop_index(op.f('ix_directorofme_auth_profile__permissions_read_0'), table_name='directorofme_auth_profile')
    op.drop_index(op.f('ix_directorofme_auth_profile__permissions_delete_1'), table_name='directorofme_auth_profile')
    op.drop_index(op.f('ix_directorofme_auth_profile__permissions_delete_0'), table_name='directorofme_auth_profile')
    op.drop_table('directorofme_auth_profile')
    op.drop_index(op.f('ix_directorofme_auth_license__permissions_write_1'), table_name='directorofme_auth_license')
    op.drop_index(op.f('ix_directorofme_auth_license__permissions_write_0'), table_name='directorofme_auth_license')
    op.drop_index(op.f('ix_directorofme_auth_license__permissions_read_1'), table_name='directorofme_auth_license')
    op.drop_index(op.f('ix_directorofme_auth_license__permissions_read_0'), table_name='directorofme_auth_license')
    op.drop_index(op.f('ix_directorofme_auth_license__permissions_delete_1'), table_name='directorofme_auth_license')
    op.drop_index(op.f('ix_directorofme_auth_license__permissions_delete_0'), table_name='directorofme_auth_license')
    op.drop_table('directorofme_auth_license')
    op.drop_index(op.f('ix_directorofme_auth_installed_app__permissions_write_1'), table_name='directorofme_auth_installed_app')
    op.drop_index(op.f('ix_directorofme_auth_installed_app__permissions_write_0'), table_name='directorofme_auth_installed_app')
    op.drop_index(op.f('ix_directorofme_auth_installed_app__permissions_read_1'), table_name='directorofme_auth_installed_app')
    op.drop_index(op.f('ix_directorofme_auth_installed_app__permissions_read_0'), table_name='directorofme_auth_installed_app')
    op.drop_index(op.f('ix_directorofme_auth_installed_app__permissions_delete_1'), table_name='directorofme_auth_installed_app')
    op.drop_index(op.f('ix_directorofme_auth_installed_app__permissions_delete_0'), table_name='directorofme_auth_installed_app')
    op.drop_table('directorofme_auth_installed_app')
    op.drop_table('directorofme_auth_group_to_group')
    op.drop_index(op.f('ix_directorofme_auth_group_scope_name'), table_name='directorofme_auth_group')
    op.drop_index(op.f('ix_directorofme_auth_group_name'), table_name='directorofme_auth_group')
    op.drop_index(op.f('ix_directorofme_auth_group__permissions_write_1'), table_name='directorofme_auth_group')
    op.drop_index(op.f('ix_directorofme_auth_group__permissions_write_0'), table_name='directorofme_auth_group')
    op.drop_index(op.f('ix_directorofme_auth_group__permissions_read_1'), table_name='directorofme_auth_group')
    op.drop_index(op.f('ix_directorofme_auth_group__permissions_read_0'), table_name='directorofme_auth_group')
    op.drop_index(op.f('ix_directorofme_auth_group__permissions_delete_1'), table_name='directorofme_auth_group')
    op.drop_index(op.f('ix_directorofme_auth_group__permissions_delete_0'), table_name='directorofme_auth_group')
    op.drop_table('directorofme_auth_group')
    op.drop_index(op.f('ix_directorofme_auth_app_slug'), table_name='directorofme_auth_app')
    op.drop_index(op.f('ix_directorofme_auth_app__permissions_write_1'), table_name='directorofme_auth_app')
    op.drop_index(op.f('ix_directorofme_auth_app__permissions_write_0'), table_name='directorofme_auth_app')
    op.drop_index(op.f('ix_directorofme_auth_app__permissions_read_1'), table_name='directorofme_auth_app')
    op.drop_index(op.f('ix_directorofme_auth_app__permissions_read_0'), table_name='directorofme_auth_app')
    op.drop_index(op.f('ix_directorofme_auth_app__permissions_delete_1'), table_name='directorofme_auth_app')
    op.drop_index(op.f('ix_directorofme_auth_app__permissions_delete_0'), table_name='directorofme_auth_app')
    op.drop_table('directorofme_auth_app')
    # ### end Alembic commands ###
