"""empty message

Revision ID: 9b85d192b76c
Revises: edb1f4bba89e
Create Date: 2018-05-27 19:52:48.604618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b85d192b76c'
down_revision = '8c0968acb34f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directorofme_auth_app', sa.Column('public_key', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directorofme_auth_app', 'public_key')
    # ### end Alembic commands ###
