"""empty message

Revision ID: a1ef8411799b
Revises: 
Create Date: 2018-02-01 19:36:26.426258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ef8411799b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_write_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_write_1', sa.String(length=20), nullable=True),
    sa.Column('_permissions_read_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_read_1', sa.String(length=20), nullable=True),
    sa.Column('_permissions_delete_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_delete_1', sa.String(length=20), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('callback_url', sa.String(length=255), nullable=True),
    sa.Column('config_schema', sa.dialects.postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_app__permissions_delete_0'), 'app', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_app__permissions_delete_1'), 'app', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_app__permissions_read_0'), 'app', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_app__permissions_read_1'), 'app', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_app__permissions_write_0'), 'app', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_app__permissions_write_1'), 'app', ['_permissions_write_1'], unique=False)
    op.create_index(op.f('ix_app_slug'), 'app', ['slug'], unique=True)
    op.create_table('group',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_write_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_write_1', sa.String(length=20), nullable=True),
    sa.Column('_permissions_read_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_read_1', sa.String(length=20), nullable=True),
    sa.Column('_permissions_delete_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_delete_1', sa.String(length=20), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=34), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('system', 'scope', 'feature', 'data', name='grouptypes'), nullable=False),
    sa.Column('scope', sa.String(length=34), nullable=True),
    sa.Column('scope_permission', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name', 'type'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('scope', 'scope_permission')
    )
    op.create_index(op.f('ix_group__permissions_delete_0'), 'group', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_group__permissions_delete_1'), 'group', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_group__permissions_read_0'), 'group', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_group__permissions_read_1'), 'group', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_group__permissions_write_0'), 'group', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_group__permissions_write_1'), 'group', ['_permissions_write_1'], unique=False)
    op.create_table('group_to_group',
    sa.Column('parent_group_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('member_group_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['member_group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['parent_group_id'], ['group.id'], )
    )
    op.create_table('installed_app',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_write_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_write_1', sa.String(length=20), nullable=True),
    sa.Column('_permissions_read_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_read_1', sa.String(length=20), nullable=True),
    sa.Column('_permissions_delete_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_delete_1', sa.String(length=20), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('app_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('config', sa.dialects.postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installed_app__permissions_delete_0'), 'installed_app', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_installed_app__permissions_delete_1'), 'installed_app', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_installed_app__permissions_read_0'), 'installed_app', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_installed_app__permissions_read_1'), 'installed_app', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_installed_app__permissions_write_0'), 'installed_app', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_installed_app__permissions_write_1'), 'installed_app', ['_permissions_write_1'], unique=False)
    op.create_table('license',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_write_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_write_1', sa.String(length=20), nullable=True),
    sa.Column('_permissions_read_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_read_1', sa.String(length=20), nullable=True),
    sa.Column('_permissions_delete_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_delete_1', sa.String(length=20), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('managing_group_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('valid_through', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['managing_group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license__permissions_delete_0'), 'license', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_license__permissions_delete_1'), 'license', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_license__permissions_read_0'), 'license', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_license__permissions_read_1'), 'license', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_license__permissions_write_0'), 'license', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_license__permissions_write_1'), 'license', ['_permissions_write_1'], unique=False)
    op.create_table('profile',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_write_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_write_1', sa.String(length=20), nullable=True),
    sa.Column('_permissions_read_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_read_1', sa.String(length=20), nullable=True),
    sa.Column('_permissions_delete_0', sa.String(length=20), nullable=True),
    sa.Column('_permissions_delete_1', sa.String(length=20), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('preferences', sa.dialects.postgresql.JSON(), nullable=True),
    sa.Column('group_of_one_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_of_one_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_profile__permissions_delete_0'), 'profile', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_profile__permissions_delete_1'), 'profile', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_profile__permissions_read_0'), 'profile', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_profile__permissions_read_1'), 'profile', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_profile__permissions_write_0'), 'profile', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_profile__permissions_write_1'), 'profile', ['_permissions_write_1'], unique=False)
    op.create_table('requested_scopes',
    sa.Column('app_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('group_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], )
    )
    op.create_table('granted_scopes',
    sa.Column('installed_app_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('group_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['installed_app_id'], ['installed_app.id'], )
    )
    op.create_table('group_to_license',
    sa.Column('license_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('group_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['license.id'], )
    )
    op.create_table('profile_to_license',
    sa.Column('license_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.Column('profile_id', sa.dialects.postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['license.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_to_license')
    op.drop_table('group_to_license')
    op.drop_table('granted_scopes')
    op.drop_table('requested_scopes')
    op.drop_index(op.f('ix_profile__permissions_write_1'), table_name='profile')
    op.drop_index(op.f('ix_profile__permissions_write_0'), table_name='profile')
    op.drop_index(op.f('ix_profile__permissions_read_1'), table_name='profile')
    op.drop_index(op.f('ix_profile__permissions_read_0'), table_name='profile')
    op.drop_index(op.f('ix_profile__permissions_delete_1'), table_name='profile')
    op.drop_index(op.f('ix_profile__permissions_delete_0'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_license__permissions_write_1'), table_name='license')
    op.drop_index(op.f('ix_license__permissions_write_0'), table_name='license')
    op.drop_index(op.f('ix_license__permissions_read_1'), table_name='license')
    op.drop_index(op.f('ix_license__permissions_read_0'), table_name='license')
    op.drop_index(op.f('ix_license__permissions_delete_1'), table_name='license')
    op.drop_index(op.f('ix_license__permissions_delete_0'), table_name='license')
    op.drop_table('license')
    op.drop_index(op.f('ix_installed_app__permissions_write_1'), table_name='installed_app')
    op.drop_index(op.f('ix_installed_app__permissions_write_0'), table_name='installed_app')
    op.drop_index(op.f('ix_installed_app__permissions_read_1'), table_name='installed_app')
    op.drop_index(op.f('ix_installed_app__permissions_read_0'), table_name='installed_app')
    op.drop_index(op.f('ix_installed_app__permissions_delete_1'), table_name='installed_app')
    op.drop_index(op.f('ix_installed_app__permissions_delete_0'), table_name='installed_app')
    op.drop_table('installed_app')
    op.drop_table('group_to_group')
    op.drop_index(op.f('ix_group__permissions_write_1'), table_name='group')
    op.drop_index(op.f('ix_group__permissions_write_0'), table_name='group')
    op.drop_index(op.f('ix_group__permissions_read_1'), table_name='group')
    op.drop_index(op.f('ix_group__permissions_read_0'), table_name='group')
    op.drop_index(op.f('ix_group__permissions_delete_1'), table_name='group')
    op.drop_index(op.f('ix_group__permissions_delete_0'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_app_slug'), table_name='app')
    op.drop_index(op.f('ix_app__permissions_write_1'), table_name='app')
    op.drop_index(op.f('ix_app__permissions_write_0'), table_name='app')
    op.drop_index(op.f('ix_app__permissions_read_1'), table_name='app')
    op.drop_index(op.f('ix_app__permissions_read_0'), table_name='app')
    op.drop_index(op.f('ix_app__permissions_delete_1'), table_name='app')
    op.drop_index(op.f('ix_app__permissions_delete_0'), table_name='app')
    op.drop_table('app')
    # ### end Alembic commands ###
