"""empty message

Revision ID: aab68eaf91ba
Revises: ed2428cbaf89
Create Date: 2018-02-09 17:26:06.293818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab68eaf91ba'
down_revision = 'ed2428cbaf89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_to_license', sa.Column('created', sa.DateTime(), nullable=True))
    op.execute("UPDATE \"profile_to_license\" SET created = NOW();")
    op.alter_column('profile_to_license',
                    sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_to_license', 'created')
    # ### end Alembic commands ###
