"""empty message

Revision ID: b4b5d1ef9c65
Revises: edb1f4bba89e
Create Date: 2018-02-06 00:23:24.664665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b5d1ef9c65'
down_revision = 'a1ef8411799b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('scope_name', sa.String(length=34), nullable=True))
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=True)
    op.create_index(op.f('ix_group_scope_name'), 'group', ['scope_name'], unique=False)

    # migrate data from scope to scope_name
    op.execute("UPDATE \"group\" SET scope_name = scope;")

    op.drop_constraint('group_name_key', 'group', type_='unique')
    op.drop_constraint('group_scope_scope_permission_key', 'group', type_='unique')
    op.create_unique_constraint(None, 'group', ['scope_name', 'scope_permission'])
    op.drop_column('group', 'scope')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('scope', sa.VARCHAR(length=34), autoincrement=False, nullable=True))

    op.drop_constraint(None, 'group', type_='unique')
    op.create_unique_constraint('group_scope_scope_permission_key', 'group', ['scope', 'scope_permission'])
    op.create_unique_constraint('group_name_key', 'group', ['name'])

    # migrate data from scope_name to scope
    op.execute("UPDATE \"group\" SET scope = scope_name;")

    op.drop_index(op.f('ix_group_scope_name'), table_name='group')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_column('group', 'scope_name')
    # ### end Alembic commands ###
