"""empty message

Revision ID: e912f822e790
Revises: edb1f4bba89e
Create Date: 2018-06-02 15:48:14.797301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e912f822e790'
down_revision = '9b85d192b76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directorofme_auth_slack_bot',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('_permissions_write_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_write_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_read_1', sa.String(length=50), nullable=True),
    sa.Column('_permissions_delete_0', sa.String(length=50), nullable=True),
    sa.Column('_permissions_delete_1', sa.String(length=50), nullable=True),
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('installing_slack_user_id', sa.String(length=25), nullable=False),
    sa.Column('installing_profile_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('team_id', sa.String(length=25), nullable=False),
    sa.Column('bot_id', sa.String(length=25), nullable=False),
    sa.Column('encrypted_access_token', sa.String(length=4096), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String(length=25)), nullable=False),
    sa.ForeignKeyConstraint(['installing_profile_id'], ['directorofme_auth_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id')
    )
    op.create_index(op.f('ix_directorofme_auth_slack_bot__permissions_delete_0'), 'directorofme_auth_slack_bot', ['_permissions_delete_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_slack_bot__permissions_delete_1'), 'directorofme_auth_slack_bot', ['_permissions_delete_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_slack_bot__permissions_read_0'), 'directorofme_auth_slack_bot', ['_permissions_read_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_slack_bot__permissions_read_1'), 'directorofme_auth_slack_bot', ['_permissions_read_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_slack_bot__permissions_write_0'), 'directorofme_auth_slack_bot', ['_permissions_write_0'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_slack_bot__permissions_write_1'), 'directorofme_auth_slack_bot', ['_permissions_write_1'], unique=False)
    op.create_index(op.f('ix_directorofme_auth_slack_bot_team_id'), 'directorofme_auth_slack_bot', ['team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directorofme_auth_slack_bot_team_id'), table_name='directorofme_auth_slack_bot')
    op.drop_index(op.f('ix_directorofme_auth_slack_bot__permissions_write_1'), table_name='directorofme_auth_slack_bot')
    op.drop_index(op.f('ix_directorofme_auth_slack_bot__permissions_write_0'), table_name='directorofme_auth_slack_bot')
    op.drop_index(op.f('ix_directorofme_auth_slack_bot__permissions_read_1'), table_name='directorofme_auth_slack_bot')
    op.drop_index(op.f('ix_directorofme_auth_slack_bot__permissions_read_0'), table_name='directorofme_auth_slack_bot')
    op.drop_index(op.f('ix_directorofme_auth_slack_bot__permissions_delete_1'), table_name='directorofme_auth_slack_bot')
    op.drop_index(op.f('ix_directorofme_auth_slack_bot__permissions_delete_0'), table_name='directorofme_auth_slack_bot')
    op.drop_table('directorofme_auth_slack_bot')
    # ### end Alembic commands ###
